### ISSUE TITLE
how to make multiple turrets? (bullets can be fired in all the directions)

### ISSUE THREAD

**Issue by CXP-2024** [Yao-class-cpp-studio/battle_game_2024#13]
多重炮塔

**Comment by JwsfSJyx** [comment]
不知道我的branch 能否满足这一要求（
![d0c5a4ceeb6f47cc7a5bc1924d646b0](https://github.com/user-attachments/assets/7cc62e43-b400-4df2-a1a4-ccad7e24c21b)

**Comment by CXP-2024** [comment]
感觉没问题！
