### ISSUE TITLE
Add the ability for the bullet's speed to stack with the tank's original speed

### ISSUE THREAD

**Issue by Damocleser-L** [Yao-class-cpp-studio/battle_game_2024#30]
In real life the bullet's speed is definitely related with tank's original speed, but our current design does not take this into account. I want to  add this function so that the game would be more realistic.

**Comment by AuSY0201** [comment]
Hi! I've updated the implementation of my tank based on your issue. Check whether updates in #28 is what you want!

**Comment by Damocleser-L** [comment]
Thank you so much for your assistance with the issue. Your implementation has truly enhanced the game, and I greatly appreciate your commitment. I hope you find this project enjoyable and continue to develop more impactful features.
